## Q1

In [1]:
import numpy as np

In [2]:
def get_vendermonde(arr,N):
    out = np.column_stack([arr ** (N-i-1) for i in range(N)])
    print(out)
    

In [3]:
arr = np.array([5,4,3,2,1])

In [4]:
type(arr)

numpy.ndarray

In [5]:
get_vendermonde(arr,N=4)

[[125  25   5   1]
 [ 64  16   4   1]
 [ 27   9   3   1]
 [  8   4   2   1]
 [  1   1   1   1]]


## Q2

In [6]:
def moving_avg(arr,k):
    out = np.row_stack([int(sum(arr[i:i+k])/k) for i in range(len(arr)-k-1)])
    print(out)
    

In [7]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [8]:
k =3

In [9]:
moving_avg(arr,k)

[[ 5]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [28]
 [49]
 [72]
 [84]]
